import { useState } from 'react';
import { Search } from 'lucide-react';
import { getGetStockHistoryQueryKey, useGetMarketStocks, useGetStockHistory } from '@workspace/api-client-react';
import { Sidebar } from '@/components/sidebar';

export default function HistoricalExplorer() {
  const [symbol, setSymbol] = useState('GP');
  const stocksQuery = useGetMarketStocks();
  const historyQuery = useGetStockHistory(symbol, { query: { queryKey: getGetStockHistoryQueryKey(symbol), enabled: Boolean(symbol) } });
  const history = historyQuery.data ?? [];
  return <div className="flex min-h-[100dvh] bg-background text-foreground"><Sidebar active="historical" /><main className="min-w-0 flex-1 terminal-grid px-5 py-8 md:px-10"><div className="mx-auto max-w-6xl"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">DSE / Historical explorer</p><h1 className="mt-1 text-3xl font-semibold">Historical price explorer</h1><p className="mt-2 text-sm text-muted-foreground">Search saved OHLCV history collected by the ingestion pipeline.</p><section className="mt-7 rounded-lg border border-border bg-card p-5"><label className="block text-xs font-semibold" htmlFor="historical-symbol">Stock symbol</label><div className="mt-2 flex max-w-md gap-2"><div className="relative flex-1"><Search size={14} className="absolute left-3 top-3 text-muted-foreground" /><input id="historical-symbol" value={symbol} onChange={(event) => setSymbol(event.target.value.toUpperCase())} className="h-10 w-full rounded-md border border-border bg-background pl-9 pr-3 font-mono text-sm uppercase" /></div><select aria-label="Choose stock" value={symbol} onChange={(event) => setSymbol(event.target.value)} className="h-10 rounded-md border border-border bg-background px-3 text-sm">{stocksQuery.data?.map((stock) => <option key={stock.symbol} value={stock.symbol}>{stock.symbol}</option>)}</select></div></section><section className="mt-5 rounded-lg border border-border bg-card p-5"><h2 className="font-semibold">{symbol || 'Select a symbol'} history</h2>{historyQuery.isLoading ? <p className="py-12 text-sm text-muted-foreground">Loading saved history…</p> : historyQuery.isError ? <p className="py-12 text-sm text-rose-600">Historical data could not be loaded.</p> : !history.length ? <p className="py-12 text-sm text-muted-foreground">No saved history yet. Run the ingestion worker and refresh this page.</p> : <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="pb-3">Date</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume</th></tr></thead><tbody>{history.slice().reverse().map((row) => <tr key={row.time} className="border-b border-border/60 font-mono text-xs"><td className="py-3">{row.time}</td><td>{row.open}</td><td>{row.high}</td><td>{row.low}</td><td>{row.close}</td><td>{row.volume.toLocaleString()}</td></tr>)}</tbody></table></div>}</section></div></main></div>;
}
