import { RefreshCw } from 'lucide-react';
import { getGetIngestionLogsQueryKey, getGetIngestionStatusQueryKey, getGetIngestionTrackerQueryKey, useGetIngestionLogs, useGetIngestionStatus, useGetIngestionTracker } from '@workspace/api-client-react';
import { Sidebar } from '@/components/sidebar';

export default function IngestionMonitor() {
  const statusQuery = useGetIngestionStatus({ query: { queryKey: getGetIngestionStatusQueryKey(), refetchInterval: 15000 } });
  const trackerQuery = useGetIngestionTracker({ query: { queryKey: getGetIngestionTrackerQueryKey(), refetchInterval: 15000 } });
  const logsQuery = useGetIngestionLogs({ query: { queryKey: getGetIngestionLogsQueryKey(), refetchInterval: 15000 } });
  const status = statusQuery.data;
  const refresh = () => void Promise.all([statusQuery.refetch(), trackerQuery.refetch(), logsQuery.refetch()]);
  return <div className="flex min-h-[100dvh] bg-background text-foreground"><Sidebar active="ingestion" /><main className="min-w-0 flex-1 terminal-grid px-5 py-8 md:px-10"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">DSE / Ingestion monitor</p><h1 className="mt-1 text-3xl font-semibold">Data collection monitor</h1><p className="mt-2 text-sm text-muted-foreground">Track every symbol collected and stored in Supabase.</p></div><button type="button" onClick={refresh} className="inline-flex items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-xs font-semibold"><RefreshCw size={14} className={statusQuery.isFetching ? 'animate-spin' : ''} /> Refresh</button></div><section className="mt-7 grid gap-4 sm:grid-cols-4">{[['Total', status?.total], ['Completed', status?.completed], ['Pending', status?.pending], ['Failed', status?.failed]].map(([label, value]) => <div key={String(label)} className="rounded-lg border border-border bg-card p-5"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold">{value ?? '—'}</p></div>)}</section><section className="mt-5 rounded-lg border border-border bg-card p-5"><h2 className="font-semibold">Symbol queue</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="border-b text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="pb-3">Symbol</th><th>Status</th><th>Records saved</th><th>Updated</th></tr></thead><tbody>{trackerQuery.data?.map((row) => <tr key={row.symbol} className="border-b border-border/60 font-mono text-xs"><td className="py-3">{row.symbol}</td><td>{row.status}</td><td>{row.totalRecordsInserted}</td><td>{new Date(row.lastUpdated).toLocaleString()}</td></tr>)}</tbody></table>{!trackerQuery.data?.length && <p className="py-7 text-sm text-muted-foreground">No ingestion queue records yet.</p>}</div></section><section className="mt-5 rounded-lg border border-border bg-card p-5"><h2 className="font-semibold">Worker activity</h2><div className="mt-4 space-y-2">{logsQuery.data?.map((log) => <div key={`${log.time}-${log.symbol}`} className="flex flex-wrap gap-x-4 gap-y-1 rounded border border-border/70 px-3 py-2 font-mono text-xs"><span>{new Date(log.time).toLocaleString()}</span><span className="font-semibold">{log.symbol}</span><span>{log.status}</span><span className="text-muted-foreground">{log.message}</span></div>)}{!logsQuery.data?.length && <p className="text-sm text-muted-foreground">No worker logs yet.</p>}</div></section></div></main></div>;
}
